version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: complisec
      POSTGRES_USER: complisec
      POSTGRES_PASSWORD: complisec123
      # Принудительная установка UTF-8 кодировки
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8"
      LC_ALL: "ru_RU.UTF-8"
      LANG: "ru_RU.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U complisec -d complisec"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://complisec:complisec123@postgres:5432/complisec?sslmode=disable&client_encoding=UTF8
      - JWT_SECRET=your-secret-key-here
      - PORT=8080
      # Принудительная установка UTF-8 для Go приложения
      - LC_ALL=ru_RU.UTF-8
      - LANG=ru_RU.UTF-8
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./storage:/root/storage
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: