services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: risknexus
      POSTGRES_USER: risknexus
      POSTGRES_PASSWORD: risknexus123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U risknexus -d risknexus"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://risknexus:risknexus123@postgres:5432/risknexus?sslmode=disable
      JWT_SECRET: your-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8080/api
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    command: npm run dev

  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - "11434:8080"
    deploy:
      restart_policy:
        condition: always
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  postgres_data:
  open-webui:


